name: Issue

on:
  schedule:
    - cron: '0 0 */5 * *'  # Runs at midnight every 5 days
  workflow_dispatch:

jobs:
  issue:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Create Issue
      id: created-issue
      run: |
        ISSUE_URL=$(gh issue create --title "Issue" --body "")
        ISSUE_NUMBER=$(echo "$ISSUE_URL" | grep -oP '\d+$')
    
    - name: Close Issue
      run: |
        gh issue close ${{ steps.created-issue.outputs.ISSUE_NUMBER }}
